# Generated by Django 4.2.3 on 2023-07-10 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('activity', 'Activity'), ('event', 'Event')], max_length=255)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='images/')),
                ('notice', models.CharField(max_length=255)),
            ],
        ),
    ]
