# Generated by Django 4.2.3 on 2023-07-10 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('equipements', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('commodation', models.CharField(max_length=100)),
                ('localisation', models.URLField()),
                ('price', models.IntegerField()),
                ('notice', models.CharField(max_length=255)),
                ('city', models.ManyToManyField(to='hotel.city')),
                ('files', models.ManyToManyField(to='files.files')),
                ('roomtype', models.ManyToManyField(to='hotel.roomtype')),
            ],
        ),
    ]
