# Generated by Django 4.2.3 on 2023-07-10 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('pack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('participant_number', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('pack', models.ForeignKey(db_column='pack_id', on_delete=django.db.models.deletion.CASCADE, to='pack.pack')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
