# Generated by Django 4.2.3 on 2023-07-10 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('program', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('personalisée', 'Personalisée')], max_length=50)),
                ('notice', models.CharField(max_length=255)),
                ('cities', models.ManyToManyField(to='hotel.city')),
                ('hotels', models.ManyToManyField(to='hotel.hotel')),
                ('programs', models.ManyToManyField(to='program.program')),
                ('services', models.ManyToManyField(to='service.service')),
            ],
        ),
    ]
